# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class AddExerciseRefToPersonalRecord < ActiveRecord::Migration
  def change
    add_reference :personal_records, :exercise, index: true
  end
end
