# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class AddNametoWorkoutSession < ActiveRecord::Migration
  def change
     add_column :workout_sessions, :name, :string
  end
end
