# _create_workout_sessions.rb
# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class CreateWorkoutSessions < ActiveRecord::Migration
  def change
    create_table :workout_sessions do |t|
      t.timestamps null: false
    end
  end
end
