# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class AddCompletedToWorkoutSet < ActiveRecord::Migration
  def change
    add_column :workout_sets, :is_complete, :boolean
  end
end
