# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class FixResistanceColumn < ActiveRecord::Migration
  def change
    change_column :workout_set_groups, :resistance, :integer, :default => 45
  end
end
