# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class Adddefaultanddescriptiontoroutine < ActiveRecord::Migration
  def change
    change_column :routines, :is_public, :boolean, :default => false
  end
end
