# By: Mathew Allen
# Mostly generated by rake
# Defines the database migration
class RenameResistance < ActiveRecord::Migration
  def change
    rename_column :workout_sets, :amount_of_resistance, :resistance
  end
end
